// ═══════════════════════════════════════════════════════════════════════════════
// FIREALIVE — MFA (TOTP) Self-Service Routes
//
// Authenticated users manage their own TOTP enrollment and recovery
// codes via these endpoints. All operations are scoped to req.user.id
// -- the routes never accept a user_id parameter, so a user cannot
// enroll/disable another user's MFA or consume their recovery codes.
// (Admin-mediated reset for lost devices is a separate flow that
// must itself require two-person approval; not implemented here.)
//
// Endpoints:
//   GET    /api/mfa/status                    { enrolled, in_enrollment }
//   POST   /api/mfa/enroll-start              -> { secret_base32, otpauth_url, qr_png_data_url }
//   POST   /api/mfa/enroll-confirm            { totp_code } -> { enrolled_at, recovery_codes }
//   POST   /api/mfa/verify                    { totp_code } -> { verified, step }
//   POST   /api/mfa/disable                   { totp_code } -> { disabled_at }
//   POST   /api/mfa/use-recovery              { recovery_code } -> { verified, remaining }
//   GET    /api/mfa/recovery-status           -> { generated, remaining, total }
//   POST   /api/mfa/regenerate-recovery       { totp_code } -> { recovery_codes }
//
// Auth:
//   This file is mounted with authMiddleware(['analyst', 'lead', 'admin',
//   'developer']) in server/index.js. Any authenticated user can manage
//   their own MFA. No per-handler role tightening -- the user_id scoping
//   to req.user.id is the security boundary.
//
// Why a top-level /api/mfa rather than /api/auth/mfa:
//   - /api/auth is mounted without authMiddleware (login is unauthenticated)
//   - These endpoints all require an authenticated JWT
//   - Splitting into /api/mfa lets index.js cleanly apply authMiddleware
//     at the mount point without per-handler exemptions
//   - The frontend's existing /api/auth/mfa-verify path is dead code that
//     was never wired server-side; this file replaces it with the canonical
//     /api/mfa/verify. Frontend will be updated to match in a later commit.
//
// Audit log:
//   The TOTP service writes operation-specific events (TOTP_ENROLL_START,
//   TOTP_ENROLL_CONFIRM_OK/FAIL, TOTP_VERIFY_OK/FAIL/REPLAY/REPLAY_RACE/
//   BLOCKED, TOTP_DISABLED, TOTP_RECOVERY_GENERATED, TOTP_RECOVERY_REGENERATED,
//   TOTP_RECOVERY_USED, TOTP_RECOVERY_FAIL, TOTP_RECOVERY_BLOCKED,
//   TOTP_RECOVERY_EXHAUSTED, TOTP_RECOVERY_RACE). The global auditMiddleware
//   in index.js writes the HTTP-level audit row. This file does not
//   duplicate-log.
//
// AGPL-3.0-or-later
// ═══════════════════════════════════════════════════════════════════════════════

const router = require('express').Router();
const qrcode = require('qrcode');
const { getDb } = require('../db/init');
const { logger } = require('../services/logger');
const totp = require('../services/totp');
const webauthn = require('../services/webauthn');
const { auditLog } = require('../middleware/audit');

// ── Helpers ──────────────────────────────────────────────────────────────────

function totpCodeToHttpStatus(code) {
  switch (code) {
    case totp.CODES.INVALID_INPUT:
      return 400;
    case totp.CODES.USER_NOT_FOUND:
      return 404;
    case totp.CODES.NOT_ENROLLED:
    case totp.CODES.RECOVERY_CODES_EXHAUSTED:
    case totp.CODES.NO_RECOVERY_CODES_GENERATED:
      return 403;
    case totp.CODES.ALREADY_ENROLLED:
      return 409;
    case totp.CODES.CODE_INVALID:
    case totp.CODES.CODE_REPLAY:
    case totp.CODES.RECOVERY_CODE_INVALID:
      return 401;
    case totp.CODES.RECOVERY_CODE_RACE:
      return 409;
    case totp.CODES.LOCKED_OUT:
      return 429;
    case totp.CODES.ENCRYPTION_NOT_CONFIGURED:
      return 500;
    default:
      return 500;
  }
}

function sendTotpError(res, err) {
  const status = totpCodeToHttpStatus(err.code);
  const body = { error: err.message, code: err.code };
  if (err.detail !== undefined) body.detail = err.detail;
  res.status(status).json(body);
}

function validateTotpCode(value) {
  if (typeof value !== 'string') return 'totp_code must be a string';
  if (!/^\d{6}$/.test(value)) return 'totp_code must be exactly 6 digits';
  return null; // valid
}

function validateRecoveryCode(value) {
  if (typeof value !== 'string') return 'recovery_code must be a string';
  // 14-char hyphenated alphanumeric format generated by the service
  // (e.g. "K7QM-3RTX-W9HJ"). Permissive 1-64 char check matches the
  // service's own input validation; format-correctness is enforced
  // by the bcrypt comparison failing on bogus input. The 64-char
  // upper bound rejects pathological inputs (huge strings) before
  // paying bcrypt cost.
  if (value.length === 0 || value.length > 64) return 'recovery_code must be 1-64 characters';
  return null;
}

// ── GET /api/mfa/status ─────────────────────────────────────────────────────
//
// Returns the calling user's TOTP enrollment state. Used by the frontend
// to decide whether to show the "Set up MFA" wizard, the "Enter code"
// confirmation screen, or the "Disable MFA" management view.
router.get('/status', (req, res) => {
  try {
    const db = getDb();
    const enrolled = totp.isEnrolled(db, req.user.id);
    const inEnrollment = totp.isInEnrollment(db, req.user.id);
    return res.json({ enrolled, in_enrollment: inEnrollment });
  } catch (err) {
    logger.error('MFA status failed', { userId: req.user.id, error: err.message });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/enroll-start ──────────────────────────────────────────────
//
// Generates a fresh TOTP secret for the calling user and stores it
// (encrypted) in users.totp_secret. Returns the base32 secret + an
// otpauth:// URI that the frontend renders as a QR code for the
// authenticator app to scan.
//
// Server-side QR PNG: the response also includes qr_png_data_url, a
// complete `data:image/png;base64,...` URL the frontend can use
// directly with <img src={qr_png_data_url} />. Generating the PNG
// server-side lets the MC / AC / GD frontends share a single QR
// rendering path without each shipping its own QR library; the
// otpauth_url is also returned so authenticator apps that don't scan
// (or environments where camera access is restricted) can use manual
// key entry as a fallback.
//
// SECURITY: the secret is returned ONCE in the response. The frontend
// must not log it, persist it client-side, or display it after the user
// has confirmed enrollment. The backend stores only the encrypted form;
// retrieving the plaintext later is impossible without re-running enroll.
//
// Async handler: qrcode.toDataURL is Promise-based (the qrcode lib has
// no truly synchronous PNG rendering path). Express handles async
// route handlers fine.
router.post('/enroll-start', async (req, res) => {
  try {
    const db = getDb();
    const result = totp.enrollStart(db, req.user.id, {
      issuer: 'FireAlive',
      account_label: req.user.name || req.user.id,
      client_ip: req.ip || null,
    });

    // Render the otpauth URL as a base64 PNG data URL for the frontend.
    // QR rendering failure is non-fatal: the otpauth_url alone is
    // sufficient for manual key entry. We log the failure and return
    // the response without the data URL.
    let qrPngDataUrl = null;
    try {
      qrPngDataUrl = await qrcode.toDataURL(result.otpauth_url, {
        errorCorrectionLevel: 'M',  // medium ECC -- balances density vs. resilience
        margin: 2,                  // standard quiet zone
        width: 256,                 // 256px square; scales fine in the UI
      });
    } catch (qrErr) {
      logger.warn('QR PNG render failed; returning otpauth_url without PNG', {
        userId: req.user.id,
        error: qrErr.message,
      });
    }

    return res.status(201).json({
      secret_base32: result.secret_base32,
      otpauth_url: result.otpauth_url,
      qr_png_data_url: qrPngDataUrl,
    });
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA enroll-start failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/enroll-confirm ────────────────────────────────────────────
//
// Body: { totp_code: string (6 digits, required) }
//
// Confirms enrollment by verifying the user's first OTP from their
// authenticator app. On success, sets users.totp_enrolled_at, seeds
// users.totp_last_used_step (so the same code cannot later be used for
// step-up MFA), AND generates 10 single-use recovery codes that are
// returned in the response for one-time display.
//
// Response: { enrolled_at, recovery_codes }
//
//   recovery_codes is an array of 10 plaintext strings in 4-4-4
//   alphanumeric format (e.g. "K7QM-3RTX-W9HJ"). The frontend MUST
//   display these to the user once and not persist them; they are
//   bcrypt-hashed at rest server-side, so even the server cannot
//   retrieve them later. If the user loses these codes before
//   recording them, they must use POST /api/mfa/regenerate-recovery
//   to generate a fresh batch (which invalidates any prior codes).
//
// Failed confirmations do not count toward the verify() lockout
// (enrollment is one-shot; locking would just frustrate users typing
// codes a second too late).
router.post('/enroll-confirm', (req, res) => {
  const code = req.body && req.body.totp_code;
  const codeError = validateTotpCode(code);
  if (codeError) {
    return res.status(400).json({ error: codeError, code: 'INVALID_INPUT' });
  }

  try {
    const db = getDb();
    const result = totp.enrollConfirm(db, req.user.id, code, req.ip || null);
    return res.json(result);
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA enroll-confirm failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/verify ────────────────────────────────────────────────────
//
// Body: { totp_code: string (6 digits, required) }
//
// General-purpose step-up verification. The same totp.verify() that
// routes/restore-approvals.js calls inline before approve. Exposed
// here for frontend flows that want to confirm MFA before navigating
// to a sensitive screen, or for clients that want to pre-flight a
// step-up before composing a privileged request body.
//
// Replay protection: a successful verify advances totp_last_used_step,
// so the same code cannot be re-used (here OR by routes/restore-
// approvals.js) within its 30-second window.
router.post('/verify', (req, res) => {
  const code = req.body && req.body.totp_code;
  const codeError = validateTotpCode(code);
  if (codeError) {
    return res.status(400).json({ error: codeError, code: 'INVALID_INPUT' });
  }

  try {
    const db = getDb();
    const result = totp.verify(db, req.user.id, code, req.ip || null);
    return res.json(result);
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA verify failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/disable ───────────────────────────────────────────────────
//
// Body: { totp_code: string (6 digits, required) }
//
// Disables MFA after verifying a valid current OTP. The OTP requirement
// prevents an attacker who has stolen a session token from also turning
// off the account's second factor.
//
// On success, clears users.totp_secret, totp_enrolled_at, and resets
// totp_last_used_step.
router.post('/disable', (req, res) => {
  const code = req.body && req.body.totp_code;
  const codeError = validateTotpCode(code);
  if (codeError) {
    return res.status(400).json({ error: codeError, code: 'INVALID_INPUT' });
  }

  try {
    const db = getDb();
    const result = totp.disable(db, req.user.id, code, req.ip || null);
    return res.json(result);
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA disable failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/use-recovery ──────────────────────────────────────────────
//
// Body: { recovery_code: string (1-64 chars, required) }
//
// Consumes a single recovery code as the MFA factor when the user does
// not have access to their TOTP authenticator. The matched code is
// removed from the user's recovery code list and the remaining count
// is decremented. The same lockout bucket as TOTP verify (totp:userId
// namespace) protects this endpoint -- attackers cannot probe the two
// factors independently.
//
// Response: { verified: true, remaining: <count> }
//
// Step-up MFA via the middleware/mfa-stepup factory accepts recovery
// codes by default; this endpoint exists for symmetry with /verify
// and for direct frontend flows that want to explicitly use a
// recovery code (e.g. a UI affordance "use recovery code instead of
// TOTP" on a re-auth modal).
router.post('/use-recovery', (req, res) => {
  const code = req.body && req.body.recovery_code;
  const codeError = validateRecoveryCode(code);
  if (codeError) {
    return res.status(400).json({ error: codeError, code: 'INVALID_INPUT' });
  }

  try {
    const db = getDb();
    const result = totp.consumeRecoveryCode(db, req.user.id, code, req.ip || null);
    return res.json(result);
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA use-recovery failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── GET /api/mfa/recovery-status ────────────────────────────────────────────
//
// Read-only status of the calling user's recovery codes. Used by the
// frontend Security section to display "X of 10 recovery codes
// remaining" and to surface a low-codes warning that prompts the user
// to regenerate.
//
// Response: { generated: boolean, remaining: number, total: number }
//
//   generated   true iff recovery codes have ever been generated for
//               this user (false until enroll-confirm succeeds).
//   remaining   count of unused codes (0 once all are consumed).
//   total       original batch size (always RECOVERY_CODE_COUNT for now).
//
// No plaintext codes are returned -- the server never has them after
// enrollment-time generation.
router.get('/recovery-status', (req, res) => {
  try {
    const db = getDb();
    const result = totp.getRecoveryCodesStatus(db, req.user.id);
    return res.json(result);
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA recovery-status failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/regenerate-recovery ───────────────────────────────────────
//
// Body: { totp_code: string (6 digits, required) }
//
// Generates a fresh batch of 10 recovery codes, invalidating ALL
// previously-issued codes for this user. Requires a valid current TOTP
// code as proof of authenticator possession -- protects against an
// attacker with a hijacked session regenerating codes (which would
// lock out the legitimate user from their own recovery path).
//
// MUST require TOTP, not a recovery code (allowing a recovery code to
// authorize regeneration would be circular: an attacker who's
// guessing a recovery code could regenerate to extend their attack
// window). The TOTP gate is enforced inside totp.regenerateRecovery
// Codes() via a verify() call; the regenerate endpoint cannot be
// protected by the mfaStepUp middleware itself because the middleware
// would also accept recovery codes by default.
//
// Response: { recovery_codes: [string, ...] }
//
//   The new plaintext codes for one-time display. Same security
//   constraints as enroll-confirm's recovery_codes field.
router.post('/regenerate-recovery', (req, res) => {
  const code = req.body && req.body.totp_code;
  const codeError = validateTotpCode(code);
  if (codeError) {
    return res.status(400).json({ error: codeError, code: 'INVALID_INPUT' });
  }

  try {
    const db = getDb();
    const codes = totp.regenerateRecoveryCodes(db, req.user.id, code, req.ip || null);
    return res.json({ recovery_codes: codes });
  } catch (err) {
    if (err instanceof totp.TotpError) return sendTotpError(res, err);
    logger.error('MFA regenerate-recovery failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ═══════════════════════════════════════════════════════════════════════════════
// B5b — FIDO2/WebAuthn passkey enrollment & management (self-service)
//
// These endpoints let an already-authenticated user enroll and manage their own
// passkeys on the session-protected /api/mfa mount. A passkey can be enrolled
// either as a PASSWORDLESS login credential (discoverable / resident key, user
// verification required — AAL3, usable on its own at /login-webauthn) or as a
// SECOND FACTOR only. The WebAuthn protocol work lives in services/webauthn.js;
// this file persists results in webauthn_credentials and enforces a lockout
// guard on removal.
//
// First-credential bootstrap (a brand-new user with no session) and break-glass
// recovery enrollment are deliberately NOT here — those callers have no session
// and are handled by a separate token-gated path.
// ═══════════════════════════════════════════════════════════════════════════════

// Count a user's usable LOGIN methods, optionally excluding one passkey (used to
// preview the effect of a deletion). A login method is: a password (if set), an
// active issued certificate, or a passwordless passkey. Second-factor-only
// passkeys are NOT login methods and never count here.
function countLoginMethodsExcluding(db, userId, excludePasskeyId) {
  const u = db.prepare('SELECT password_hash FROM users WHERE id = ?').get(userId);
  const hasPassword = u && u.password_hash ? 1 : 0;
  const pwlessPasskeys = db.prepare(
    'SELECT COUNT(*) AS c FROM webauthn_credentials WHERE user_id = ? AND is_passwordless = 1 AND id != ?'
  ).get(userId, excludePasskeyId || '').c;
  const activeCerts = db.prepare(
    "SELECT COUNT(*) AS c FROM issued_certs WHERE user_id = ? AND status = 'active'"
  ).get(userId).c;
  return hasPassword + pwlessPasskeys + activeCerts;
}

// ── POST /api/mfa/passkey/register-options ──────────────────────────────────
// Begin passkey enrollment for the calling user. Body: { passwordless?: bool }.
// A passwordless passkey is requested as a discoverable resident key with user
// verification required; a second-factor passkey uses softer settings.
router.post('/passkey/register-options', async (req, res) => {
  try {
    const db = getDb();
    const passwordless = !!(req.body && req.body.passwordless);
    const rp = webauthn.getRpConfig(db);
    const existing = db.prepare(
      'SELECT credential_id AS credentialId, transports FROM webauthn_credentials WHERE user_id = ?'
    ).all(req.user.id);
    const { options, challengeToken } = await webauthn.beginRegistration({
      rp,
      userId: req.user.id,
      userName: req.user.name || req.user.id,
      existingCredentials: existing,
      residentKey: passwordless ? 'required' : 'discouraged',
      userVerification: passwordless ? 'required' : 'preferred',
    });
    return res.json({ options, challengeToken });
  } catch (err) {
    logger.error('Passkey register-options failed', { userId: req.user.id, error: err.message });
    return res.status(500).json({ error: 'could not start passkey enrollment', code: 'INTERNAL' });
  }
});

// ── POST /api/mfa/passkey/register-verify ───────────────────────────────────
// Finish passkey enrollment. Body: { response, challengeToken, passwordless?, label? }.
// For a passwordless passkey, user verification is required at verification time
// so the credential is genuinely MFA-complete. Persists the credential and
// returns its public identifier.
router.post('/passkey/register-verify', async (req, res) => {
  try {
    const db = getDb();
    const body = req.body || {};
    if (!body.response || !body.challengeToken) {
      return res.status(400).json({ error: 'response and challengeToken required' });
    }
    const passwordless = !!body.passwordless;
    const rp = webauthn.getRpConfig(db);
    let result;
    try {
      result = await webauthn.finishRegistration({
        rp,
        response: body.response,
        challengeToken: body.challengeToken,
        requireUserVerification: passwordless,
      });
    } catch (vErr) {
      return res.status(400).json({ error: 'passkey verification failed', detail: vErr.message });
    }
    if (!result.verified || !result.credential) {
      return res.status(400).json({ error: 'passkey verification failed' });
    }
    const c = result.credential;
    try {
      db.prepare(`
        INSERT INTO webauthn_credentials
          (user_id, credential_id, public_key, sign_count, transports, aaguid, is_passwordless)
        VALUES (?, ?, ?, ?, ?, ?, ?)
      `).run(
        req.user.id,
        c.credentialId,
        c.publicKey,
        c.counter || 0,
        c.transports || null,
        c.aaguid || null,
        passwordless ? 1 : 0
      );
    } catch (dbErr) {
      // UNIQUE(credential_id) violation => the authenticator is already enrolled.
      if (/UNIQUE|constraint/i.test(dbErr.message)) {
        return res.status(409).json({ error: 'this authenticator is already enrolled' });
      }
      throw dbErr;
    }
    auditLog(req.user.id, 'WEBAUTHN_PASSKEY_ENROLLED',
      `passwordless=${passwordless} cred=${String(c.credentialId).slice(0, 12)}…`, req.ip);
    return res.status(201).json({
      enrolled: true,
      passwordless,
      credential_id: c.credentialId,
      backed_up: !!c.backedUp,
      device_type: c.deviceType || null,
    });
  } catch (err) {
    logger.error('Passkey register-verify failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── GET /api/mfa/passkeys ───────────────────────────────────────────────────
// List the calling user's passkeys (no key material).
router.get('/passkeys', (req, res) => {
  try {
    const db = getDb();
    const rows = db.prepare(`
      SELECT id, credential_id, is_passwordless, aaguid, created_at, last_used_at
      FROM webauthn_credentials WHERE user_id = ?
      ORDER BY created_at DESC, rowid DESC
    `).all(req.user.id);
    return res.json({ passkeys: rows });
  } catch (err) {
    logger.error('Passkey list failed', { userId: req.user.id, error: err.message });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});

// ── DELETE /api/mfa/passkeys/:id ────────────────────────────────────────────
// Remove one of the calling user's passkeys. Refuses if it would leave the user
// with no way to authenticate (no password, no active certificate, no other
// passwordless passkey) — lockout prevention.
router.delete('/passkeys/:id', (req, res) => {
  try {
    const db = getDb();
    const id = req.params.id;
    const cred = db.prepare('SELECT * FROM webauthn_credentials WHERE id = ? AND user_id = ?').get(id, req.user.id);
    if (!cred) return res.status(404).json({ error: 'passkey not found' });
    if (countLoginMethodsExcluding(db, req.user.id, id) === 0) {
      return res.status(409).json({
        error: 'cannot remove your last login credential; enroll another authenticator first',
        code: 'LAST_CREDENTIAL',
      });
    }
    db.prepare('DELETE FROM webauthn_credentials WHERE id = ? AND user_id = ?').run(id, req.user.id);
    auditLog(req.user.id, 'WEBAUTHN_PASSKEY_REMOVED', `cred=${String(cred.credential_id).slice(0, 12)}…`, req.ip);
    return res.json({ removed: true, id });
  } catch (err) {
    logger.error('Passkey delete failed', { userId: req.user.id, error: err.message, stack: err.stack });
    return res.status(500).json({ error: 'internal error', code: 'INTERNAL' });
  }
});


module.exports = router;
