// ═══════════════════════════════════════════════════════════════════════════════
// FIREALIVE — Cloud & IaC Templates: Azure Bicep (R3k C14)
//
// Azure-only.
// ═══════════════════════════════════════════════════════════════════════════════

function render(snapshot, provider) {
  if (provider !== 'azure') {
    throw new Error(`bicep template: Azure-only, got '${provider}'`);
  }
  const main = [
    '// FireAlive Azure deployment (Bicep)',
    `// Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}, version=${snapshot.version.version}`,
    '',
    "@description('Azure region')",
    "param location string = resourceGroup().location",
    '',
    "@description('Container image reference')",
    "param firealiveImage string = 'ghcr.io/petermancina/firealive:latest'",
    '',
    "@description('32-byte hex KEK for v2 backup engine')",
    "@secure()",
    "param tier1EncryptionKey string",
    '',
    "@description('JWT signing secret')",
    "@secure()",
    "param jwtSecret string",
    '',
    "@description('Object id of the operator allowed to read secrets from the Key Vault')",
    "param operatorObjectId string",
    '',
    "var kvName = 'firealive-kv-${uniqueString(resourceGroup().id)}'",
    "var aciName = 'firealive-aci'",
    '',
    "resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {",
    "  name: kvName",
    "  location: location",
    "  properties: {",
    "    sku: { family: 'A', name: 'standard' }",
    "    tenantId: subscription().tenantId",
    "    accessPolicies: [",
    "      {",
    "        tenantId: subscription().tenantId",
    "        objectId: operatorObjectId",
    "        permissions: { secrets: [ 'get', 'list', 'set' ] }",
    "      }",
    "    ]",
    "  }",
    "}",
    '',
    "resource kvTier1 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {",
    "  parent: kv",
    "  name: 'tier1-encryption-key'",
    "  properties: { value: tier1EncryptionKey }",
    "}",
    '',
    "resource kvJwt 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {",
    "  parent: kv",
    "  name: 'jwt-secret'",
    "  properties: { value: jwtSecret }",
    "}",
    '',
    "resource aci 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {",
    "  name: aciName",
    "  location: location",
    "  properties: {",
    "    osType: 'Linux'",
    "    ipAddress: {",
    "      type: 'Public'",
    "      dnsNameLabel: aciName",
    "      ports: [ { port: 3000, protocol: 'TCP' } ]",
    "    }",
    "    containers: [",
    "      {",
    "        name: 'firealive'",
    "        properties: {",
    "          image: firealiveImage",
    "          resources: { requests: { cpu: 1, memoryInGB: 2 } }",
    "          ports: [ { port: 3000 } ]",
    "          environmentVariables: [",
    "            { name: 'TIER1_ENCRYPTION_KEY', secureValue: tier1EncryptionKey }",
    "            { name: 'JWT_SECRET', secureValue: jwtSecret }",
    "          ]",
    "        }",
    "      }",
    "    ]",
    "  }",
    "}",
    '',
    "output firealiveEndpoint string = 'https://${aci.properties.ipAddress.fqdn}:3000'",
    '',
  ].join('\n');
  return {
    files: [{ path: 'main.bicep', content: main }],
  };
}

module.exports = { render };
