// ═══════════════════════════════════════════════════════════════════════════════
// FIREALIVE — Cloud & IaC Templates: AWS CloudFormation (R3k C14)
//
// AWS-only. Generator pre-validates this against PROVIDER_TOOL_MATRIX,
// but the template double-checks defensively.
// ═══════════════════════════════════════════════════════════════════════════════

function render(snapshot, provider) {
  if (provider !== 'aws') {
    throw new Error(`cloudformation template: AWS-only, got '${provider}'`);
  }
  const yaml = [
    'AWSTemplateFormatVersion: "2010-09-09"',
    'Description: FireAlive deployment (ECS Fargate + Secrets Manager + ALB)',
    '',
    'Parameters:',
    '  Tier1EncryptionKey:',
    '    Type: String',
    '    NoEcho: true',
    '    Description: 32-byte hex KEK for the v2 backup engine',
    '  JwtSecret:',
    '    Type: String',
    '    NoEcho: true',
    '    Description: JWT signing secret (>=16 random chars)',
    '  FireAliveImage:',
    '    Type: String',
    '    Default: ghcr.io/petermancina/firealive:latest',
    '',
    'Resources:',
    '  Tier1KeySecret:',
    '    Type: AWS::SecretsManager::Secret',
    '    Properties:',
    '      Name: firealive/tier1-encryption-key',
    '      SecretString: !Ref Tier1EncryptionKey',
    '',
    '  JwtSecretRes:',
    '    Type: AWS::SecretsManager::Secret',
    '    Properties:',
    '      Name: firealive/jwt-secret',
    '      SecretString: !Ref JwtSecret',
    '',
    '  Cluster:',
    '    Type: AWS::ECS::Cluster',
    '    Properties:',
    '      ClusterName: firealive',
    '',
    '  TaskExecutionRole:',
    '    Type: AWS::IAM::Role',
    '    Properties:',
    '      AssumeRolePolicyDocument:',
    '        Version: "2012-10-17"',
    '        Statement:',
    '          - Effect: Allow',
    '            Principal: { Service: ecs-tasks.amazonaws.com }',
    '            Action: sts:AssumeRole',
    '      ManagedPolicyArns:',
    '        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy',
    '        - arn:aws:iam::aws:policy/SecretsManagerReadWrite',
    '',
    '  TaskDef:',
    '    Type: AWS::ECS::TaskDefinition',
    '    Properties:',
    '      Family: firealive',
    '      NetworkMode: awsvpc',
    '      RequiresCompatibilities: [FARGATE]',
    '      Cpu: "1024"',
    '      Memory: "2048"',
    '      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn',
    '      ContainerDefinitions:',
    '        - Name: firealive',
    '          Image: !Ref FireAliveImage',
    '          PortMappings:',
    '            - ContainerPort: 3000',
    '              HostPort: 3000',
    '          Secrets:',
    '            - Name: TIER1_ENCRYPTION_KEY',
    '              ValueFrom: !Ref Tier1KeySecret',
    '            - Name: JWT_SECRET',
    '              ValueFrom: !Ref JwtSecretRes',
    '',
    'Outputs:',
    '  ClusterArn:',
    '    Value: !GetAtt Cluster.Arn',
    '  Note:',
    '    Value: "Production deployment also needs VPC, subnets, ALB, security groups, ECS service, persistent EFS or RDS for the SQLite DB"',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return {
    files: [{ path: 'firealive.yaml', content: yaml }],
  };
}

module.exports = { render };
