// ═══════════════════════════════════════════════════════════════════════════════
// FIREALIVE — Cloud & IaC Templates: Terraform (R3k C14)
//
// Per-provider Terraform templates. Each template produces a minimal
// but valid Terraform configuration deploying FireAlive as a Docker
// container on the chosen cloud provider's compute service. Operators
// customize before applying.
//
// ALL TEMPLATES USE STRING-ARRAY .join('\n') for content blocks
// containing Terraform's `${...}` interpolation syntax — this is the
// canonical Babel-safe pattern carried forward from Phase B even
// though backend Node files don't pass through Babel. Consistent
// pattern across the templates directory.
// ═══════════════════════════════════════════════════════════════════════════════

const PROVIDER_TEMPLATES = {
  aws: renderAws,
  azure: renderAzure,
  gcp: renderGcp,
  hetzner: renderHetzner,
  ovhcloud: renderOvhcloud,
  exoscale: renderExoscale,
};

function render(snapshot, provider) {
  const fn = PROVIDER_TEMPLATES[provider];
  if (!fn) throw new Error(`terraform template: unsupported provider '${provider}'`);
  return { files: fn(snapshot) };
}

function variablesTf() {
  return [
    'variable "tier1_encryption_key" {',
    '  description = "32-byte hex KEK for the v2 backup engine"',
    '  type        = string',
    '  sensitive   = true',
    '}',
    '',
    'variable "jwt_secret" {',
    '  description = "JWT signing secret (>=16 random chars)"',
    '  type        = string',
    '  sensitive   = true',
    '}',
    '',
    'variable "firealive_image" {',
    '  description = "Docker image reference for the FireAlive server"',
    '  type        = string',
    '  default     = "ghcr.io/petermancina/firealive:latest"',
    '}',
    '',
    'variable "instance_size" {',
    '  description = "Provider-specific compute size identifier"',
    '  type        = string',
    '}',
    '',
  ].join('\n');
}

function outputsTf() {
  return [
    'output "firealive_endpoint" {',
    '  description = "Public endpoint URL for the FireAlive server"',
    '  value       = local.firealive_endpoint',
    '}',
    '',
  ].join('\n');
}

function renderAws(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = "us-east-1"',
    '}',
    '',
    'resource "aws_secretsmanager_secret" "tier1_key" {',
    '  name = "firealive/tier1-encryption-key"',
    '}',
    '',
    'resource "aws_secretsmanager_secret_version" "tier1_key_v" {',
    '  secret_id     = aws_secretsmanager_secret.tier1_key.id',
    '  secret_string = var.tier1_encryption_key',
    '}',
    '',
    'resource "aws_secretsmanager_secret" "jwt_secret" {',
    '  name = "firealive/jwt-secret"',
    '}',
    '',
    'resource "aws_secretsmanager_secret_version" "jwt_secret_v" {',
    '  secret_id     = aws_secretsmanager_secret.jwt_secret.id',
    '  secret_string = var.jwt_secret',
    '}',
    '',
    'resource "aws_ecs_cluster" "firealive" {',
    '  name = "firealive"',
    '}',
    '',
    'resource "aws_ecs_task_definition" "firealive" {',
    '  family                   = "firealive"',
    '  network_mode             = "awsvpc"',
    '  requires_compatibilities = ["FARGATE"]',
    '  cpu                      = "1024"',
    '  memory                   = "2048"',
    '  container_definitions    = jsonencode([{',
    '    name      = "firealive"',
    '    image     = var.firealive_image',
    '    portMappings = [{ containerPort = 3000, hostPort = 3000 }]',
    '    secrets = [',
    '      { name = "TIER1_ENCRYPTION_KEY", valueFrom = aws_secretsmanager_secret.tier1_key.arn },',
    '      { name = "JWT_SECRET",            valueFrom = aws_secretsmanager_secret.jwt_secret.arn }',
    '    ]',
    '  }])',
    '}',
    '',
    'locals {',
    '  firealive_endpoint = "https://<your-alb-dns>:3000"',
    '}',
    '',
    '# NOTE: A production deployment also needs: VPC, subnets, ALB, security',
    '# groups, ECS service, IAM execution role, CloudWatch log group, and a',
    '# persistent EFS or RDS for the SQLite DB (or RDS Postgres + the future',
    '# Postgres adapter when it lands).',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderAzure(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    azurerm = {',
    '      source  = "hashicorp/azurerm"',
    '      version = "~> 3.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "azurerm" {',
    '  features {}',
    '}',
    '',
    'resource "azurerm_resource_group" "firealive" {',
    '  name     = "firealive-rg"',
    '  location = "eastus"',
    '}',
    '',
    'resource "azurerm_key_vault" "firealive" {',
    '  name                = "firealive-kv"',
    '  resource_group_name = azurerm_resource_group.firealive.name',
    '  location            = azurerm_resource_group.firealive.location',
    '  tenant_id           = data.azurerm_client_config.current.tenant_id',
    '  sku_name            = "standard"',
    '}',
    '',
    'data "azurerm_client_config" "current" {}',
    '',
    'resource "azurerm_key_vault_secret" "tier1_key" {',
    '  name         = "tier1-encryption-key"',
    '  value        = var.tier1_encryption_key',
    '  key_vault_id = azurerm_key_vault.firealive.id',
    '}',
    '',
    'resource "azurerm_key_vault_secret" "jwt_secret" {',
    '  name         = "jwt-secret"',
    '  value        = var.jwt_secret',
    '  key_vault_id = azurerm_key_vault.firealive.id',
    '}',
    '',
    'resource "azurerm_container_group" "firealive" {',
    '  name                = "firealive"',
    '  location            = azurerm_resource_group.firealive.location',
    '  resource_group_name = azurerm_resource_group.firealive.name',
    '  os_type             = "Linux"',
    '  ip_address_type     = "Public"',
    '  dns_name_label      = "firealive-${random_id.suffix.hex}"',
    '',
    '  container {',
    '    name   = "firealive"',
    '    image  = var.firealive_image',
    '    cpu    = "1.0"',
    '    memory = "2.0"',
    '    ports { port = 3000 protocol = "TCP" }',
    '    secure_environment_variables = {',
    '      TIER1_ENCRYPTION_KEY = var.tier1_encryption_key',
    '      JWT_SECRET           = var.jwt_secret',
    '    }',
    '  }',
    '}',
    '',
    'resource "random_id" "suffix" { byte_length = 4 }',
    '',
    'locals {',
    '  firealive_endpoint = "https://${azurerm_container_group.firealive.fqdn}:3000"',
    '}',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderGcp(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    google = {',
    '      source  = "hashicorp/google"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "google" {',
    '  project = "your-gcp-project"',
    '  region  = "us-central1"',
    '}',
    '',
    'resource "google_secret_manager_secret" "tier1_key" {',
    '  secret_id = "firealive-tier1-key"',
    '  replication { auto {} }',
    '}',
    '',
    'resource "google_secret_manager_secret_version" "tier1_key_v" {',
    '  secret      = google_secret_manager_secret.tier1_key.id',
    '  secret_data = var.tier1_encryption_key',
    '}',
    '',
    'resource "google_secret_manager_secret" "jwt_secret" {',
    '  secret_id = "firealive-jwt-secret"',
    '  replication { auto {} }',
    '}',
    '',
    'resource "google_secret_manager_secret_version" "jwt_secret_v" {',
    '  secret      = google_secret_manager_secret.jwt_secret.id',
    '  secret_data = var.jwt_secret',
    '}',
    '',
    'resource "google_cloud_run_v2_service" "firealive" {',
    '  name     = "firealive"',
    '  location = "us-central1"',
    '  template {',
    '    containers {',
    '      image = var.firealive_image',
    '      ports { container_port = 3000 }',
    '      env {',
    '        name = "TIER1_ENCRYPTION_KEY"',
    '        value_source {',
    '          secret_key_ref {',
    '            secret  = google_secret_manager_secret.tier1_key.secret_id',
    '            version = "latest"',
    '          }',
    '        }',
    '      }',
    '      env {',
    '        name = "JWT_SECRET"',
    '        value_source {',
    '          secret_key_ref {',
    '            secret  = google_secret_manager_secret.jwt_secret.secret_id',
    '            version = "latest"',
    '          }',
    '        }',
    '      }',
    '    }',
    '  }',
    '}',
    '',
    'locals {',
    '  firealive_endpoint = google_cloud_run_v2_service.firealive.uri',
    '}',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderHetzner(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    hcloud = {',
    '      source  = "hetznercloud/hcloud"',
    '      version = "~> 1.45"',
    '    }',
    '  }',
    '}',
    '',
    'provider "hcloud" {',
    '  # token via HCLOUD_TOKEN env var',
    '}',
    '',
    'resource "hcloud_ssh_key" "deploy" {',
    '  name       = "firealive-deploy"',
    '  public_key = file("~/.ssh/id_ed25519.pub")',
    '}',
    '',
    'resource "hcloud_server" "firealive" {',
    '  name        = "firealive"',
    '  image       = "docker-ce"',
    '  server_type = var.instance_size',
    '  location    = "fsn1"',
    '  ssh_keys    = [hcloud_ssh_key.deploy.id]',
    '  user_data = <<-EOT',
    '    #cloud-config',
    '    write_files:',
    '      - path: /etc/firealive/.env',
    '        permissions: "0600"',
    '        content: |',
    '          TIER1_ENCRYPTION_KEY=${var.tier1_encryption_key}',
    '          JWT_SECRET=${var.jwt_secret}',
    '    runcmd:',
    '      - docker run -d --name firealive --restart=always -p 3000:3000 --env-file /etc/firealive/.env -v firealive-data:/data ${var.firealive_image}',
    '  EOT',
    '}',
    '',
    'resource "hcloud_volume" "data" {',
    '  name     = "firealive-data"',
    '  size     = 50',
    '  location = "fsn1"',
    '  format   = "ext4"',
    '}',
    '',
    'resource "hcloud_volume_attachment" "data" {',
    '  volume_id = hcloud_volume.data.id',
    '  server_id = hcloud_server.firealive.id',
    '}',
    '',
    'locals {',
    '  firealive_endpoint = "https://${hcloud_server.firealive.ipv4_address}:3000"',
    '}',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '# Secrets ship via cloud-init user_data; rotate by re-applying with new vars.',
    '# For Vault-backed secrets in production, swap the user_data block for a',
    '# vault agent installer + env file fetch.',
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderOvhcloud(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    ovh = {',
    '      source  = "ovh/ovh"',
    '      version = "~> 0.40"',
    '    }',
    '  }',
    '}',
    '',
    'provider "ovh" {',
    '  endpoint = "ovh-eu"',
    '}',
    '',
    'resource "ovh_cloud_project_instance" "firealive" {',
    '  service_name = "your-ovh-project-id"',
    '  region       = "GRA9"',
    '  name         = "firealive"',
    '  flavor_name  = var.instance_size',
    '  image_name   = "Docker"',
    '  user_data = base64encode(join("\\n", [',
    '    "#cloud-config",',
    '    "write_files:",',
    '    "  - path: /etc/firealive/.env",',
    '    "    permissions: \\"0600\\"",',
    '    "    content: |",',
    '    "      TIER1_ENCRYPTION_KEY=${var.tier1_encryption_key}",',
    '    "      JWT_SECRET=${var.jwt_secret}",',
    '    "runcmd:",',
    '    "  - docker run -d --name firealive --restart=always -p 3000:3000 --env-file /etc/firealive/.env -v firealive-data:/data ${var.firealive_image}",',
    '  ]))',
    '}',
    '',
    'locals {',
    '  firealive_endpoint = "https://${ovh_cloud_project_instance.firealive.address}:3000"',
    '}',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderExoscale(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    exoscale = {',
    '      source  = "exoscale/exoscale"',
    '      version = "~> 0.55"',
    '    }',
    '  }',
    '}',
    '',
    'provider "exoscale" {',
    '  # key/secret via EXOSCALE_API_KEY / EXOSCALE_API_SECRET env vars',
    '}',
    '',
    'data "exoscale_template" "docker" {',
    '  zone   = "ch-gva-2"',
    '  name   = "Linux Ubuntu 22.04 LTS 64-bit"',
    '  filter = "featured"',
    '}',
    '',
    'resource "exoscale_compute_instance" "firealive" {',
    '  zone        = "ch-gva-2"',
    '  name        = "firealive"',
    '  template_id = data.exoscale_template.docker.id',
    '  type        = var.instance_size',
    '  disk_size   = 50',
    '  user_data = <<-EOT',
    '    #cloud-config',
    '    package_update: true',
    '    packages:',
    '      - docker.io',
    '    write_files:',
    '      - path: /etc/firealive/.env',
    '        permissions: "0600"',
    '        content: |',
    '          TIER1_ENCRYPTION_KEY=${var.tier1_encryption_key}',
    '          JWT_SECRET=${var.jwt_secret}',
    '    runcmd:',
    '      - systemctl enable --now docker',
    '      - docker run -d --name firealive --restart=always -p 3000:3000 --env-file /etc/firealive/.env -v firealive-data:/data ${var.firealive_image}',
    '  EOT',
    '}',
    '',
    'locals {',
    '  firealive_endpoint = "https://${exoscale_compute_instance.firealive.public_ip_address}:3000"',
    '}',
    '',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join('\n');
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

module.exports = { render };
