// ===============================================================================
// FIREALIVE GD -- Cloud & IaC Templates: Azure Bicep (B6c PR-5 twin)
//
// Azure-only. Provisions FireAlive on a CONFIDENTIAL VM with Trusted Launch:
// AMD SEV-SNP memory encryption (securityType ConfidentialVM), a vTPM (TPM 2.0
// hardware root of trust), secure boot, and VM guest-state disk encryption.
// Cloud mode REQUIRES confidential computing and is attested at boot, so the
// managed-container path (Azure Container Instances) is intentionally not
// emitted.
//
// Secrets live in Key Vault and are fetched at boot by the VM managed identity;
// they are never placed in custom_data in cleartext, because the
// confidential-VM model assumes the provider can read instance metadata but not
// guest memory. cloud-init is a Bicep multi-line string with format()
// placeholders, so the template carries no backslash escapes.
// ===============================================================================

const NL = String.fromCharCode(10);

function render(snapshot, provider) {
  if (provider !== 'azure') {
    throw new Error(`bicep template: Azure-only, got '${provider}'`);
  }
  const main = [
    '// FireAlive Azure deployment (Bicep) - confidential VM with Trusted Launch',
    `// Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}, version=${snapshot.version.version}`,
    '',
    "@description('Azure region')",
    "param location string = resourceGroup().location",
    '',
    "@description('Container image reference')",
    '',
    "@description('Confidential VM size (for example Standard_DC2as_v5)')",
    "param instanceSize string = 'Standard_DC2as_v5'",
    '',
    "@description('Admin username for the VM')",
    "param adminUsername string = 'azureuser'",
    '',
    "@description('SSH public key for the admin user')",
    "param adminSshPublicKey string",
    '',
    "@description('32-byte hex KEK for v2 backup engine')",
    "@secure()",
    "param gdEncryptionKey string",
    '',
    "@description('JWT signing secret')",
    "@secure()",
    "param gdJwtSecret string",
    '',
    "@description('Object id of the operator allowed to read secrets from the Key Vault')",
    "param operatorObjectId string",
    '',
    "var kvName = 'firealive-gd-kv-${uniqueString(resourceGroup().id)}'",
    "var vmName = 'firealive-vm'",
    '',
    "// cloud-init: {0} = Key Vault name (filled by format()).",
    "var cloudConfig = '''",
    '#cloud-config',
    'runcmd:',
    '  - mkdir -p /etc/firealive-gd',
    '  - az login --identity --allow-no-subscriptions',
    '  - TIER1=$(az keyvault secret show --vault-name {0} --name encryption-key --query value -o tsv)',
    '  - JWT=$(az keyvault secret show --vault-name {0} --name jwt-secret --query value -o tsv)',
    '  - umask 077',
    '  - echo "GD_ENCRYPTION_KEY=$TIER1" > /etc/firealive-gd/.env',
    '  - echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '  - echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '  - systemctl enable --now firealive-gd',
    "'''",
    '',
    "resource kv 'Microsoft.KeyVault/vaults@2023-07-01' = {",
    "  name: kvName",
    "  location: location",
    "  properties: {",
    "    sku: { family: 'A', name: 'standard' }",
    "    tenantId: subscription().tenantId",
    "    accessPolicies: [",
    "      {",
    "        tenantId: subscription().tenantId",
    "        objectId: operatorObjectId",
    "        permissions: { secrets: [ 'get', 'list', 'set' ] }",
    "      }",
    "    ]",
    "  }",
    "}",
    '',
    "resource kvTier1 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {",
    "  parent: kv",
    "  name: 'encryption-key'",
    "  properties: { value: gdEncryptionKey }",
    "}",
    '',
    "resource kvJwt 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {",
    "  parent: kv",
    "  name: 'jwt-secret'",
    "  properties: { value: gdJwtSecret }",
    "}",
    '',
    "resource vnet 'Microsoft.Network/virtualNetworks@2023-09-01' = {",
    "  name: 'firealive-vnet'",
    "  location: location",
    "  properties: {",
    "    addressSpace: { addressPrefixes: [ '10.42.0.0/16' ] }",
    "    subnets: [",
    "      { name: 'firealive-subnet', properties: { addressPrefix: '10.42.1.0/24' } }",
    "    ]",
    "  }",
    "}",
    '',
    "resource pip 'Microsoft.Network/publicIPAddresses@2023-09-01' = {",
    "  name: 'firealive-pip'",
    "  location: location",
    "  properties: { publicIPAllocationMethod: 'Static' }",
    "}",
    '',
    "resource nic 'Microsoft.Network/networkInterfaces@2023-09-01' = {",
    "  name: 'firealive-nic'",
    "  location: location",
    "  properties: {",
    "    ipConfigurations: [",
    "      {",
    "        name: 'primary'",
    "        properties: {",
    "          subnet: { id: vnet.properties.subnets[0].id }",
    "          publicIPAddress: { id: pip.id }",
    "          privateIPAllocationMethod: 'Dynamic'",
    "        }",
    "      }",
    "    ]",
    "  }",
    "}",
    '',
    "// Confidential VM (SEV-SNP) with Trusted Launch: vTPM (TPM 2.0 root of",
    "// trust) + secure boot + VM guest-state disk encryption.",
    "resource vm 'Microsoft.Compute/virtualMachines@2023-09-01' = {",
    "  name: vmName",
    "  location: location",
    "  identity: { type: 'SystemAssigned' }",
    "  properties: {",
    "    hardwareProfile: { vmSize: instanceSize }",
    "    securityProfile: {",
    "      securityType: 'ConfidentialVM'",
    "      uefiSettings: { vTpmEnabled: true, secureBootEnabled: true }",
    "    }",
    "    storageProfile: {",
    "      imageReference: {",
    "        publisher: 'Canonical'",
    "        offer: 'ubuntu-24_04-lts-cvm'",
    "        sku: 'cvm'",
    "        version: 'latest'",
    "      }",
    "      osDisk: {",
    "        createOption: 'FromImage'",
    "        managedDisk: {",
    "          storageAccountType: 'StandardSSD_LRS'",
    "          securityProfile: { securityEncryptionType: 'VMGuestStateOnly' }",
    "        }",
    "      }",
    "    }",
    "    osProfile: {",
    "      computerName: 'firealive'",
    "      adminUsername: adminUsername",
    "      customData: base64(format(cloudConfig, kvName))",
    "      linuxConfiguration: {",
    "        disablePasswordAuthentication: true",
    "        ssh: {",
    "          publicKeys: [",
    "            { path: '/home/${adminUsername}/.ssh/authorized_keys', keyData: adminSshPublicKey }",
    "          ]",
    "        }",
    "      }",
    "    }",
    "    networkProfile: { networkInterfaces: [ { id: nic.id } ] }",
    "  }",
    "  tags: { DeploymentMode: 'cloud' }",
    "}",
    '',
    "// Grant the VM managed identity read access to the secrets (separate",
    "// resource to break the VM <-> Key Vault dependency cycle).",
    "resource kvVmAccess 'Microsoft.KeyVault/vaults/accessPolicies@2023-07-01' = {",
    "  parent: kv",
    "  name: 'add'",
    "  properties: {",
    "    accessPolicies: [",
    "      {",
    "        tenantId: subscription().tenantId",
    "        objectId: vm.identity.principalId",
    "        permissions: { secrets: [ 'get' ] }",
    "      }",
    "    ]",
    "  }",
    "}",
    '',
    "output gdEndpoint string = 'https://${pip.properties.ipAddress}:4001'",
    '',
  ].join(NL);
  return {
    files: [{ path: 'main.bicep', content: main }],
  };
}

module.exports = { render };
