// ===============================================================================
// FIREALIVE GD -- Cloud & IaC Templates: Pulumi TypeScript (B6c PR-5 twin)
//
// Per-provider Pulumi templates emitting index.ts + Pulumi.yaml + package.json.
// Operators run `npm install && pulumi up`. Each template provisions the FireAlive GD server
// on a CONFIDENTIAL VM with a vTPM hardware root of trust: AMD SEV-SNP +
// NitroTPM on AWS, an Azure Confidential VM with Trusted Launch (vTPM + secure
// boot), and a GCP Confidential VM with Shielded VM (vTPM). Cloud mode REQUIRES
// confidential computing and is attested at boot, so managed-container compute
// (ECS, Container Instances, Cloud Run) is intentionally not emitted.
//
// Secrets live in the provider key/secret store and are fetched at boot by the
// instance identity (IAM role / managed identity / service account); they are
// never placed in user_data in cleartext, because the confidential-VM model
// assumes the provider can read instance metadata but not guest memory.
//
// Content is built as arrays of lines joined by NL (a literal newline). Emitted
// cloud-init is a TS template literal with real newlines, so the templates
// carry no backslash escapes.
// ===============================================================================

const NL = String.fromCharCode(10);

const PROVIDER_FNS = {
  aws: renderAws,
  azure: renderAzure,
  gcp: renderGcp,
};

function render(snapshot, provider) {
  const fn = PROVIDER_FNS[provider];
  if (!fn) throw new Error(`pulumi template: unsupported provider '${provider}'`);
  return { files: fn(snapshot) };
}

function pulumiYaml(provider) {
  return [
    'name: firealive',
    'runtime: nodejs',
    'description: FireAlive deployment (Pulumi / TypeScript)',
    `# Provider: ${provider}`,
    '',
  ].join(NL);
}

function packageJson(provider) {
  const deps = {
    aws:   '"@pulumi/aws": "^6.0.0"',
    azure: '"@pulumi/azure-native": "^2.0.0"',
    gcp:   '"@pulumi/gcp": "^7.0.0"',
  };
  return [
    '{',
    '  "name": "firealive-pulumi",',
    '  "main": "index.ts",',
    '  "dependencies": {',
    '    "@pulumi/pulumi": "^3.100.0",',
    `    ${deps[provider]}`,
    '  },',
    '  "devDependencies": {',
    '    "@types/node": "^20.0.0",',
    '    "typescript": "^5.0.0"',
    '  }',
    '}',
    '',
  ].join(NL);
}

function renderAws(snapshot) {
  const idx = [
    'import * as pulumi from "@pulumi/pulumi";',
    'import * as aws from "@pulumi/aws";',
    '',
    'const cfg = new pulumi.Config();',
    'const gdKekKey = cfg.requireSecret("gdEncryptionKey");',
    'const gdJwtSecret = cfg.requireSecret("gdJwtSecret");',
    '// SEV-SNP-capable instance type (for example m6a / c6a / r6a).',
    'const instanceSize = cfg.require("instanceSize");',
    '',
    'const gdKekSecret = new aws.secretsmanager.Secret("firealive-tier1", { name: "firealive-gd/encryption-key" });',
    'new aws.secretsmanager.SecretVersion("firealive-tier1-v", {',
    '    secretId: gdKekSecret.id,',
    '    secretString: gdKekKey,',
    '});',
    '',
    'const gdJwtSecretRes = new aws.secretsmanager.Secret("firealive-jwt", { name: "firealive-gd/jwt-secret" });',
    'new aws.secretsmanager.SecretVersion("firealive-jwt-v", {',
    '    secretId: gdJwtSecretRes.id,',
    '    secretString: gdJwtSecret,',
    '});',
    '',
    '// UEFI AMI with TPM 2.0 support; NitroTPM presents as the guest TPM.',
    'const ami = aws.ec2.getAmiOutput({',
    '    mostRecent: true,',
    '    owners: ["amazon"],',
    '    filters: [',
    '        { name: "name", values: ["al2023-ami-*-x86_64"] },',
    '        { name: "tpm-support", values: ["v2.0"] },',
    '    ],',
    '});',
    '',
    'const role = new aws.iam.Role("firealive-gd-instance", {',
    '    assumeRolePolicy: JSON.stringify({',
    '        Version: "2012-10-17",',
    '        Statement: [{ Action: "sts:AssumeRole", Effect: "Allow", Principal: { Service: "ec2.amazonaws.com" } }],',
    '    }),',
    '});',
    'new aws.iam.RolePolicy("firealive-gd-read-secrets", {',
    '    role: role.id,',
    '    policy: pulumi.all([gdKekSecret.arn, gdJwtSecretRes.arn]).apply(([a, b]) => JSON.stringify({',
    '        Version: "2012-10-17",',
    '        Statement: [{ Action: "secretsmanager:GetSecretValue", Effect: "Allow", Resource: [a, b] }],',
    '    })),',
    '});',
    'const profile = new aws.iam.InstanceProfile("firealive-gd-instance", { role: role.name });',
    '',
    '// On-demand only: cloud mode refuses spot / autoscaled / ephemeral-fleet',
    '// instances, so do NOT place this in an autoscaling group or spot request.',
    'const userData = `#cloud-config',
    'runcmd:',
    '  - mkdir -p /etc/firealive-gd',
    '  - TIER1=$(aws secretsmanager get-secret-value --secret-id firealive-gd/encryption-key --query SecretString --output text)',
    '  - JWT=$(aws secretsmanager get-secret-value --secret-id firealive-gd/jwt-secret --query SecretString --output text)',
    '  - umask 077',
    '  - echo "GD_ENCRYPTION_KEY=$TIER1" > /etc/firealive-gd/.env',
    '  - echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '  - echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '  - systemctl enable --now firealive-gd`;',
    '',
    '// AMD SEV-SNP confidential VM with NitroTPM (TPM 2.0 root of trust).',
    'const server = new aws.ec2.Instance("firealive", {',
    '    ami: ami.id,',
    '    instanceType: instanceSize,',
    '    iamInstanceProfile: profile.name,',
    '    cpuOptions: { amdSevSnp: "enabled" },',
    '    metadataOptions: { httpTokens: "required" },',
    '    userData: userData,',
    '    tags: { Name: "firealive", DeploymentMode: "cloud" },',
    '});',
    '',
    'export const endpoint = pulumi.interpolate`https://${server.publicIp}:4001`;',
    'export const note = "Production deployment also needs a VPC, subnet, security group, an EBS data volume or RDS, and Docker preinstalled in the AMI";',
    `// Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'index.ts', content: idx },
    { path: 'Pulumi.yaml', content: pulumiYaml('aws') },
    { path: 'package.json', content: packageJson('aws') },
  ];
}

function renderAzure(snapshot) {
  const idx = [
    'import * as pulumi from "@pulumi/pulumi";',
    'import * as azure from "@pulumi/azure-native";',
    '',
    'const cfg = new pulumi.Config();',
    'const gdKekKey = cfg.requireSecret("gdEncryptionKey");',
    'const gdJwtSecret = cfg.requireSecret("gdJwtSecret");',
    '// Confidential VM size (for example Standard_DC2as_v5).',
    'const instanceSize = cfg.get("instanceSize") ?? "Standard_DC2as_v5";',
    '',
    'const rg = new azure.resources.ResourceGroup("firealive-rg", { location: "eastus" });',
    '',
    'const kv = new azure.keyvault.Vault("firealive-gd-kv", {',
    '    vaultName: "firealive-gd-kv",',
    '    resourceGroupName: rg.name,',
    '    properties: {',
    '        sku: { family: "A", name: "standard" },',
    '        tenantId: "<your-tenant-id>",',
    '        accessPolicies: [],',
    '        enableRbacAuthorization: true,',
    '    },',
    '});',
    '',
    '// Store the secrets; the VM managed identity reads them at boot.',
    'new azure.keyvault.Secret("encryption-key", {',
    '    resourceGroupName: rg.name,',
    '    vaultName: kv.name,',
    '    secretName: "encryption-key",',
    '    properties: { value: gdKekKey },',
    '});',
    'new azure.keyvault.Secret("jwt-secret", {',
    '    resourceGroupName: rg.name,',
    '    vaultName: kv.name,',
    '    secretName: "jwt-secret",',
    '    properties: { value: gdJwtSecret },',
    '});',
    '',
    'const vnet = new azure.network.VirtualNetwork("firealive-vnet", {',
    '    resourceGroupName: rg.name,',
    '    addressSpace: { addressPrefixes: ["10.42.0.0/16"] },',
    '});',
    'const subnet = new azure.network.Subnet("firealive-subnet", {',
    '    resourceGroupName: rg.name,',
    '    virtualNetworkName: vnet.name,',
    '    addressPrefix: "10.42.1.0/24",',
    '});',
    'const pip = new azure.network.PublicIPAddress("firealive-pip", {',
    '    resourceGroupName: rg.name,',
    '    publicIPAllocationMethod: "Static",',
    '});',
    'const nic = new azure.network.NetworkInterface("firealive-nic", {',
    '    resourceGroupName: rg.name,',
    '    ipConfigurations: [{ name: "primary", subnet: { id: subnet.id }, publicIPAddress: { id: pip.id } }],',
    '});',
    '',
    'const cloudConfig = `#cloud-config',
    'runcmd:',
    '  - mkdir -p /etc/firealive-gd',
    '  - az login --identity --allow-no-subscriptions',
    '  - TIER1=$(az keyvault secret show --vault-name firealive-gd-kv --name encryption-key --query value -o tsv)',
    '  - JWT=$(az keyvault secret show --vault-name firealive-gd-kv --name jwt-secret --query value -o tsv)',
    '  - umask 077',
    '  - echo "GD_ENCRYPTION_KEY=$TIER1" > /etc/firealive-gd/.env',
    '  - echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '  - echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '  - systemctl enable --now firealive-gd`;',
    '',
    '// Confidential VM (SEV-SNP) with Trusted Launch: vTPM (TPM 2.0 root of',
    '// trust) + secure boot + VM guest-state disk encryption.',
    'const vm = new azure.compute.VirtualMachine("firealive", {',
    '    resourceGroupName: rg.name,',
    '    networkProfile: { networkInterfaces: [{ id: nic.id }] },',
    '    identity: { type: "SystemAssigned" },',
    '    hardwareProfile: { vmSize: instanceSize },',
    '    securityProfile: {',
    '        securityType: "ConfidentialVM",',
    '        uefiSettings: { vTpmEnabled: true, secureBootEnabled: true },',
    '    },',
    '    storageProfile: {',
    '        imageReference: { publisher: "Canonical", offer: "ubuntu-24_04-lts-cvm", sku: "cvm", version: "latest" },',
    '        osDisk: {',
    '            createOption: "FromImage",',
    '            managedDisk: { securityProfile: { securityEncryptionType: "VMGuestStateOnly" } },',
    '        },',
    '    },',
    '    osProfile: {',
    '        computerName: "firealive",',
    '        adminUsername: "azureuser",',
    '        customData: Buffer.from(cloudConfig).toString("base64"),',
    '        linuxConfiguration: {',
    '            disablePasswordAuthentication: true,',
    '            ssh: { publicKeys: [{ keyData: "<your-ssh-public-key>", path: "/home/azureuser/.ssh/authorized_keys" }] },',
    '        },',
    '    },',
    '    tags: { DeploymentMode: "cloud" },',
    '});',
    '',
    'export const publicIpName = pip.name;',
    'export const note = "Grant the VM managed identity Get access on the Key Vault secrets before first boot";',
    `// Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'index.ts', content: idx },
    { path: 'Pulumi.yaml', content: pulumiYaml('azure') },
    { path: 'package.json', content: packageJson('azure') },
  ];
}

function renderGcp(snapshot) {
  const idx = [
    'import * as pulumi from "@pulumi/pulumi";',
    'import * as gcp from "@pulumi/gcp";',
    '',
    'const cfg = new pulumi.Config();',
    'const gdKekKey = cfg.requireSecret("gdEncryptionKey");',
    'const gdJwtSecret = cfg.requireSecret("gdJwtSecret");',
    '// SEV-SNP-capable machine type (n2d / c2d).',
    'const instanceSize = cfg.get("instanceSize") ?? "n2d-standard-2";',
    '',
    'const gdKekSecret = new gcp.secretmanager.Secret("tier1", {',
    '    secretId: "firealive-tier1-key",',
    '    replication: { auto: {} },',
    '});',
    'new gcp.secretmanager.SecretVersion("tier1-v", {',
    '    secret: gdKekSecret.id,',
    '    secretData: gdKekKey,',
    '});',
    'const gdJwtSecretRes = new gcp.secretmanager.Secret("jwt", {',
    '    secretId: "firealive-jwt-secret",',
    '    replication: { auto: {} },',
    '});',
    'new gcp.secretmanager.SecretVersion("jwt-v", {',
    '    secret: gdJwtSecretRes.id,',
    '    secretData: gdJwtSecret,',
    '});',
    '',
    'const sa = new gcp.serviceaccount.Account("firealive", { accountId: "firealive", displayName: "FireAlive instance" });',
    'new gcp.secretmanager.SecretIamMember("tier1-access", {',
    '    secretId: gdKekSecret.secretId,',
    '    role: "roles/secretmanager.secretAccessor",',
    '    member: pulumi.interpolate`serviceAccount:${sa.email}`,',
    '});',
    'new gcp.secretmanager.SecretIamMember("jwt-access", {',
    '    secretId: gdJwtSecretRes.secretId,',
    '    role: "roles/secretmanager.secretAccessor",',
    '    member: pulumi.interpolate`serviceAccount:${sa.email}`,',
    '});',
    '',
    'const startupScript = `#!/bin/bash',
    'set -e',
    'mkdir -p /etc/firealive-gd',
    'TIER1=$(gcloud secrets versions access latest --secret=firealive-tier1-key)',
    'JWT=$(gcloud secrets versions access latest --secret=firealive-jwt-secret)',
    'umask 077',
    'echo "GD_ENCRYPTION_KEY=$TIER1" > /etc/firealive-gd/.env',
    'echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    'echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    'systemctl enable --now firealive-gd`;',
    '',
    '// Confidential VM (SEV-SNP) with Shielded VM: vTPM (TPM 2.0 root of trust),',
    '// secure boot, and integrity monitoring. SEV-SNP terminates (no live',
    '// migration) on host maintenance.',
    'const server = new gcp.compute.Instance("firealive", {',
    '    machineType: instanceSize,',
    '    zone: "us-central1-a",',
    '    minCpuPlatform: "AMD Milan",',
    '    confidentialInstanceConfig: { enableConfidentialCompute: true, confidentialInstanceType: "SEV_SNP" },',
    '    shieldedInstanceConfig: { enableVtpm: true, enableIntegrityMonitoring: true, enableSecureBoot: true },',
    '    scheduling: { onHostMaintenance: "TERMINATE", automaticRestart: true, preemptible: false, provisioningModel: "STANDARD" },',
    '    bootDisk: { initializeParams: { image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64" } },',
    '    networkInterfaces: [{ network: "default", accessConfigs: [{}] }],',
    '    serviceAccount: { email: sa.email, scopes: ["cloud-platform"] },',
    '    metadata: { "startup-script": startupScript },',
    '    labels: { deployment_mode: "cloud" },',
    '});',
    '',
    'export const endpoint = pulumi.interpolate`https://${server.networkInterfaces[0].accessConfigs[0].natIp}:4001`;',
    `// Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'index.ts', content: idx },
    { path: 'Pulumi.yaml', content: pulumiYaml('gcp') },
    { path: 'package.json', content: packageJson('gcp') },
  ];
}

module.exports = { render };
