// ===============================================================================
// FIREALIVE GD -- Cloud & IaC Templates: Terraform (B6c PR-5 twin)
//
// Per-provider Terraform templates for AWS, Azure, and GCP. Each template
// provisions the FireAlive GD server on a CONFIDENTIAL VM with a vTPM hardware root of
// trust: AMD SEV-SNP + NitroTPM on AWS, an Azure Confidential VM with Trusted
// Launch (vTPM + secure boot), and a GCP Confidential VM with Shielded VM
// (vTPM). Cloud mode REQUIRES confidential computing and is attested at boot,
// so non-confidential and managed-container compute (ECS Fargate, Azure
// Container Instances, Cloud Run) is intentionally not emitted. Operators
// customize before applying.
//
// SECRETS AND THE CONFIDENTIAL-VM MODEL
//   The confidential-VM threat model assumes the cloud provider cannot read
//   guest memory but CAN read instance metadata / user_data. Secrets are
//   therefore stored in the provider key/secret store and fetched at boot by
//   the instance's own identity (IAM role / managed identity / service
//   account); they are never placed in user_data in cleartext.
//
// STRING-ARRAY JOINS, NO BACKSLASH ESCAPES
//   Content blocks contain Terraform's ${...} interpolation syntax, which
//   collides with a JS template literal, so each file is built as an array of
//   lines joined by NL (a literal newline). Terraform string content uses
//   plain double quotes inside single-quoted JS strings, so the templates
//   carry no backslash escapes.
// ===============================================================================

const NL = String.fromCharCode(10);

const PROVIDER_TEMPLATES = {
  aws: renderAws,
  azure: renderAzure,
  gcp: renderGcp,
};

function render(snapshot, provider) {
  const fn = PROVIDER_TEMPLATES[provider];
  if (!fn) throw new Error(`terraform template: unsupported provider '${provider}'`);
  return { files: fn(snapshot) };
}

function variablesTf() {
  return [
    'variable "gd_encryption_key" {',
    '  description = "32-byte hex KEK for the v2 backup engine"',
    '  type        = string',
    '  sensitive   = true',
    '}',
    '',
    'variable "gd_jwt_secret" {',
    '  description = "JWT signing secret (>=16 random chars)"',
    '  type        = string',
    '  sensitive   = true',
    '}',
    '',
    'variable "gd_image" {',
    '  description = "Docker image reference for the FireAlive GD server"',
    '  type        = string',
    '  default     = "ghcr.io/petermancina/firealive-gd:latest"',
    '}',
    '',
    'variable "instance_size" {',
    '  description = "Confidential-compute-capable VM size (see per-provider note)"',
    '  type        = string',
    '}',
    '',
  ].join(NL);
}

function outputsTf() {
  return [
    'output "gd_endpoint" {',
    '  description = "Public endpoint URL for the FireAlive server"',
    '  value       = local.gd_endpoint',
    '}',
    '',
  ].join(NL);
}

function renderAws(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    aws = {',
    '      source  = "hashicorp/aws"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "aws" {',
    '  region = "us-east-1"',
    '}',
    '',
    '# Confidential compute: AMD SEV-SNP memory encryption is enabled via the',
    '# cpu_options block and REQUIRES a SEV-SNP-capable instance type (for',
    '# example an m6a / c6a / r6a size in var.instance_size). The hardware root',
    '# of trust is NitroTPM, which presents to the guest as a TPM 2.0 device;',
    '# the AMI must be a UEFI image registered with TPM support (the tpm-support',
    '# filter below selects v2.0). FireAlive refuses to seal cloud mode at boot',
    '# if confidential computing is not attested.',
    '',
    'resource "aws_secretsmanager_secret" "gd_encryption_key" {',
    '  name = "firealive-gd/encryption-key"',
    '}',
    '',
    'resource "aws_secretsmanager_secret_version" "gd_encryption_key_v" {',
    '  secret_id     = aws_secretsmanager_secret.gd_encryption_key.id',
    '  secret_string = var.gd_encryption_key',
    '}',
    '',
    'resource "aws_secretsmanager_secret" "gd_jwt_secret" {',
    '  name = "firealive-gd/jwt-secret"',
    '}',
    '',
    'resource "aws_secretsmanager_secret_version" "gd_jwt_secret_v" {',
    '  secret_id     = aws_secretsmanager_secret.gd_jwt_secret.id',
    '  secret_string = var.gd_jwt_secret',
    '}',
    '',
    'data "aws_ami" "base" {',
    '  most_recent = true',
    '  owners      = ["amazon"]',
    '  filter {',
    '    name   = "name"',
    '    values = ["al2023-ami-*-x86_64"]',
    '  }',
    '  filter {',
    '    name   = "tpm-support"',
    '    values = ["v2.0"]',
    '  }',
    '}',
    '',
    'resource "aws_iam_role" "firealive_gd" {',
    '  name = "firealive-instance"',
    '  assume_role_policy = jsonencode({',
    '    Version = "2012-10-17"',
    '    Statement = [{',
    '      Action    = "sts:AssumeRole"',
    '      Effect    = "Allow"',
    '      Principal = { Service = "ec2.amazonaws.com" }',
    '    }]',
    '  })',
    '}',
    '',
    'resource "aws_iam_role_policy" "read_secrets" {',
    '  role = aws_iam_role.firealive_gd.id',
    '  policy = jsonencode({',
    '    Version = "2012-10-17"',
    '    Statement = [{',
    '      Action   = "secretsmanager:GetSecretValue"',
    '      Effect   = "Allow"',
    '      Resource = [aws_secretsmanager_secret.gd_encryption_key.arn, aws_secretsmanager_secret.gd_jwt_secret.arn]',
    '    }]',
    '  })',
    '}',
    '',
    'resource "aws_iam_instance_profile" "firealive_gd" {',
    '  name = "firealive-instance"',
    '  role = aws_iam_role.firealive_gd.name',
    '}',
    '',
    'resource "aws_instance" "firealive_gd" {',
    '  ami                  = data.aws_ami.base.id',
    '  instance_type        = var.instance_size',
    '  iam_instance_profile = aws_iam_instance_profile.firealive_gd.name',
    '',
    '  # AMD SEV-SNP confidential computing (VM memory encryption + attestation).',
    '  cpu_options {',
    '    amd_sev_snp = "enabled"',
    '  }',
    '',
    '  # Require IMDSv2; NitroTPM (TPM 2.0) is provided by the UEFI AMI above.',
    '  metadata_options {',
    '    http_tokens = "required"',
    '  }',
    '',
    '  # On-demand only. FireAlive refuses spot / autoscaled / ephemeral-fleet',
    '  # instances in cloud mode, so do NOT place this behind a spot request or',
    '  # an autoscaling group.',
    '  user_data = <<-EOT',
    '    #cloud-config',
    '    runcmd:',
    '      - mkdir -p /etc/firealive-gd',
    '      - KEK=$(aws secretsmanager get-secret-value --secret-id firealive-gd/encryption-key --query SecretString --output text)',
    '      - JWT=$(aws secretsmanager get-secret-value --secret-id firealive-gd/jwt-secret --query SecretString --output text)',
    '      - umask 077',
    '      - echo "GD_ENCRYPTION_KEY=$KEK" > /etc/firealive-gd/.env',
    '      - echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '      - echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '      - docker run -d --name firealive-gd --restart=always -p 4001:4001 --env-file /etc/firealive-gd/.env -v firealive-gd-data:/data ${var.gd_image}',
    '  EOT',
    '',
    '  tags = {',
    '    Name           = "firealive_gd"',
    '    DeploymentMode = "cloud"',
    '  }',
    '}',
    '',
    'locals {',
    '  gd_endpoint = "https://${aws_instance.firealive_gd.public_ip}:4001"',
    '}',
    '',
    '# deployment_mode = cloud is stamped into the instance env file and the',
    '# DeploymentMode tag above. NOTE: a production deployment also needs a VPC,',
    '# subnet, security group, an EBS data volume or RDS for persistence, and',
    '# Docker preinstalled in the AMI (or added via runcmd). Secrets are read',
    '# from Secrets Manager by the instance role and never placed in user_data.',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderAzure(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    azurerm = {',
    '      source  = "hashicorp/azurerm"',
    '      version = "~> 3.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "azurerm" {',
    '  features {}',
    '}',
    '',
    'data "azurerm_client_config" "current" {}',
    '',
    'resource "azurerm_resource_group" "firealive_gd" {',
    '  name     = "firealive-rg"',
    '  location = "eastus"',
    '}',
    '',
    'resource "azurerm_key_vault" "firealive_gd" {',
    '  name                = "firealive-gd-kv"',
    '  resource_group_name = azurerm_resource_group.firealive_gd.name',
    '  location            = azurerm_resource_group.firealive_gd.location',
    '  tenant_id           = data.azurerm_client_config.current.tenant_id',
    '  sku_name            = "standard"',
    '}',
    '',
    'resource "azurerm_key_vault_secret" "gd_encryption_key" {',
    '  name         = "encryption-key"',
    '  value        = var.gd_encryption_key',
    '  key_vault_id = azurerm_key_vault.firealive_gd.id',
    '}',
    '',
    'resource "azurerm_key_vault_secret" "gd_jwt_secret" {',
    '  name         = "jwt-secret"',
    '  value        = var.gd_jwt_secret',
    '  key_vault_id = azurerm_key_vault.firealive_gd.id',
    '}',
    '',
    '# Grant the VM managed identity read access to the two secrets.',
    'resource "azurerm_key_vault_access_policy" "firealive_gd" {',
    '  key_vault_id       = azurerm_key_vault.firealive_gd.id',
    '  tenant_id          = data.azurerm_client_config.current.tenant_id',
    '  object_id          = azurerm_linux_virtual_machine.firealive_gd.identity[0].principal_id',
    '  secret_permissions = ["Get"]',
    '}',
    '',
    'resource "azurerm_virtual_network" "firealive_gd" {',
    '  name                = "firealive-vnet"',
    '  address_space       = ["10.42.0.0/16"]',
    '  location            = azurerm_resource_group.firealive_gd.location',
    '  resource_group_name = azurerm_resource_group.firealive_gd.name',
    '}',
    '',
    'resource "azurerm_subnet" "firealive_gd" {',
    '  name                 = "firealive-subnet"',
    '  resource_group_name  = azurerm_resource_group.firealive_gd.name',
    '  virtual_network_name = azurerm_virtual_network.firealive_gd.name',
    '  address_prefixes     = ["10.42.1.0/24"]',
    '}',
    '',
    'resource "azurerm_public_ip" "firealive_gd" {',
    '  name                = "firealive-pip"',
    '  location            = azurerm_resource_group.firealive_gd.location',
    '  resource_group_name = azurerm_resource_group.firealive_gd.name',
    '  allocation_method   = "Static"',
    '}',
    '',
    'resource "azurerm_network_interface" "firealive_gd" {',
    '  name                = "firealive-nic"',
    '  location            = azurerm_resource_group.firealive_gd.location',
    '  resource_group_name = azurerm_resource_group.firealive_gd.name',
    '  ip_configuration {',
    '    name                          = "primary"',
    '    subnet_id                     = azurerm_subnet.firealive_gd.id',
    '    private_ip_address_allocation = "Dynamic"',
    '    public_ip_address_id          = azurerm_public_ip.firealive_gd.id',
    '  }',
    '}',
    '',
    '# Confidential VM (AMD SEV-SNP) with Trusted Launch. var.instance_size MUST',
    '# be a confidential size (for example Standard_DC2as_v5), and the image is a',
    '# confidential-compute-capable Ubuntu CVM gallery image. vTPM is the TPM 2.0',
    '# hardware root of trust; secure boot is on; the OS disk carries VM guest',
    '# state encryption.',
    'resource "azurerm_linux_virtual_machine" "firealive_gd" {',
    '  name                  = "firealive_gd"',
    '  resource_group_name   = azurerm_resource_group.firealive_gd.name',
    '  location              = azurerm_resource_group.firealive_gd.location',
    '  size                  = var.instance_size',
    '  admin_username        = "azureuser"',
    '  network_interface_ids = [azurerm_network_interface.firealive_gd.id]',
    '',
    '  vtpm_enabled        = true',
    '  secure_boot_enabled = true',
    '',
    '  admin_ssh_key {',
    '    username   = "azureuser"',
    '    public_key = file("~/.ssh/id_ed25519.pub")',
    '  }',
    '',
    '  os_disk {',
    '    caching                  = "ReadWrite"',
    '    storage_account_type     = "Standard_LRS"',
    '    security_encryption_type = "VMGuestStateOnly"',
    '  }',
    '',
    '  source_image_reference {',
    '    publisher = "Canonical"',
    '    offer     = "ubuntu-24_04-lts-cvm"',
    '    sku       = "cvm"',
    '    version   = "latest"',
    '  }',
    '',
    '  identity {',
    '    type = "SystemAssigned"',
    '  }',
    '',
    '  custom_data = base64encode(<<-EOT',
    '    #cloud-config',
    '    runcmd:',
    '      - mkdir -p /etc/firealive-gd',
    '      - az login --identity --allow-no-subscriptions',
    '      - KEK=$(az keyvault secret show --vault-name firealive-gd-kv --name encryption-key --query value -o tsv)',
    '      - JWT=$(az keyvault secret show --vault-name firealive-gd-kv --name jwt-secret --query value -o tsv)',
    '      - umask 077',
    '      - echo "GD_ENCRYPTION_KEY=$KEK" > /etc/firealive-gd/.env',
    '      - echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '      - echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '      - docker run -d --name firealive-gd --restart=always -p 4001:4001 --env-file /etc/firealive-gd/.env -v firealive-gd-data:/data ${var.gd_image}',
    '  EOT',
    '  )',
    '',
    '  tags = {',
    '    DeploymentMode = "cloud"',
    '  }',
    '}',
    '',
    'locals {',
    '  gd_endpoint = "https://${azurerm_public_ip.firealive_gd.ip_address}:4001"',
    '}',
    '',
    '# deployment_mode = cloud is stamped into the instance env file and the',
    '# DeploymentMode tag above. Secrets are read from Key Vault by the VM',
    '# managed identity and never placed in custom_data in cleartext.',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

function renderGcp(snapshot) {
  const main = [
    'terraform {',
    '  required_providers {',
    '    google = {',
    '      source  = "hashicorp/google"',
    '      version = "~> 5.0"',
    '    }',
    '  }',
    '}',
    '',
    'provider "google" {',
    '  project = "your-gcp-project"',
    '  region  = "us-central1"',
    '}',
    '',
    'resource "google_secret_manager_secret" "gd_encryption_key" {',
    '  secret_id = "firealive-tier1-key"',
    '  replication { auto {} }',
    '}',
    '',
    'resource "google_secret_manager_secret_version" "gd_encryption_key_v" {',
    '  secret      = google_secret_manager_secret.gd_encryption_key.id',
    '  secret_data = var.gd_encryption_key',
    '}',
    '',
    'resource "google_secret_manager_secret" "gd_jwt_secret" {',
    '  secret_id = "firealive-jwt-secret"',
    '  replication { auto {} }',
    '}',
    '',
    'resource "google_secret_manager_secret_version" "gd_jwt_secret_v" {',
    '  secret      = google_secret_manager_secret.gd_jwt_secret.id',
    '  secret_data = var.gd_jwt_secret',
    '}',
    '',
    'resource "google_service_account" "firealive_gd" {',
    '  account_id   = "firealive_gd"',
    '  display_name = "FireAlive instance"',
    '}',
    '',
    'resource "google_secret_manager_secret_iam_member" "gd_kek" {',
    '  secret_id = google_secret_manager_secret.gd_encryption_key.id',
    '  role      = "roles/secretmanager.secretAccessor"',
    '  member    = "serviceAccount:${google_service_account.firealive_gd.email}"',
    '}',
    '',
    'resource "google_secret_manager_secret_iam_member" "gd_jwt" {',
    '  secret_id = google_secret_manager_secret.gd_jwt_secret.id',
    '  role      = "roles/secretmanager.secretAccessor"',
    '  member    = "serviceAccount:${google_service_account.firealive_gd.email}"',
    '}',
    '',
    '# Confidential VM (AMD SEV-SNP) with Shielded VM. var.instance_size MUST be',
    '# an SEV-SNP-capable machine type (n2d / c2d) on the AMD Milan platform.',
    '# vTPM is the TPM 2.0 hardware root of trust. SEV-SNP requires the host to',
    '# terminate (not live-migrate) on maintenance.',
    'resource "google_compute_instance" "firealive_gd" {',
    '  name         = "firealive_gd"',
    '  machine_type = var.instance_size',
    '  zone         = "us-central1-a"',
    '',
    '  confidential_instance_config {',
    '    enable_confidential_compute = true',
    '    confidential_instance_type  = "SEV_SNP"',
    '  }',
    '  min_cpu_platform = "AMD Milan"',
    '',
    '  shielded_instance_config {',
    '    enable_vtpm                 = true',
    '    enable_integrity_monitoring = true',
    '    enable_secure_boot          = true',
    '  }',
    '',
    '  scheduling {',
    '    on_host_maintenance = "TERMINATE"',
    '    automatic_restart   = true',
    '    preemptible         = false',
    '    provisioning_model  = "STANDARD"',
    '  }',
    '',
    '  boot_disk {',
    '    initialize_params {',
    '      image = "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts-amd64"',
    '    }',
    '  }',
    '',
    '  network_interface {',
    '    network = "default"',
    '    access_config {}',
    '  }',
    '',
    '  service_account {',
    '    email  = google_service_account.firealive_gd.email',
    '    scopes = ["cloud-platform"]',
    '  }',
    '',
    '  metadata = {',
    '    startup-script = <<-EOT',
    '      #!/bin/bash',
    '      set -e',
    '      mkdir -p /etc/firealive-gd',
    '      KEK=$(gcloud secrets versions access latest --secret=firealive-tier1-key)',
    '      JWT=$(gcloud secrets versions access latest --secret=firealive-jwt-secret)',
    '      umask 077',
    '      echo "GD_ENCRYPTION_KEY=$KEK" > /etc/firealive-gd/.env',
    '      echo "GD_JWT_SECRET=$JWT" >> /etc/firealive-gd/.env',
    '      echo "FIREALIVE_GD_DEPLOYMENT_MODE=cloud" >> /etc/firealive-gd/.env',
    '      docker run -d --name firealive-gd --restart=always -p 4001:4001 --env-file /etc/firealive-gd/.env -v firealive-gd-data:/data ${var.gd_image}',
    '    EOT',
    '  }',
    '',
    '  labels = {',
    '    deployment_mode = "cloud"',
    '  }',
    '}',
    '',
    'locals {',
    '  gd_endpoint = "https://${google_compute_instance.firealive_gd.network_interface[0].access_config[0].nat_ip}:4001"',
    '}',
    '',
    '# deployment_mode = cloud is stamped into the instance env file and the',
    '# deployment_mode label above. Secrets are read from Secret Manager by the',
    '# instance service account and never placed in metadata in cleartext.',
    `# Snapshot at generation: users=${snapshot.users.total}, db_size_bytes=${snapshot.data.db_size_bytes}`,
    '',
  ].join(NL);
  return [
    { path: 'main.tf', content: main },
    { path: 'variables.tf', content: variablesTf() },
    { path: 'outputs.tf', content: outputsTf() },
  ];
}

module.exports = { render };
