'use strict';

/*
 * tier1-columns.js -- GENERATED by scripts/derive-tier1-registry.js.
 * DO NOT EDIT BY HAND. Regenerate: node scripts/derive-tier1-registry.js --emit mc
 *
 * The Tier-1 columns of the Management Console schema: those sealed under a KEK this
 * server holds. domain node-local uses the node own KEK; domain replicated uses the
 * shared (active) KEK. class tier1-derived is HKDF-sealed from the KEK. shape is the
 * plaintext serialization (json|utf8|raw); storage is the at-rest encoding
 * (buffer|base64|hex|envelope).
 */

const TIER1_COLUMNS = [
  { table: 'abuse_vault_chain_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'archive_chain_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'audit_chain_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'backup_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'chain_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'cloud_iac_signing_keys', column: 'private_key_wrapped', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'forensic_export_chain_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'gd_push_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'ha_node', column: 'sealed_promotion_kek', domain: 'node-local', class: 'tier1-derived', shape: 'raw', storage: 'base64' },
  { table: 'ha_node', column: 'wrap_private_sealed', domain: 'node-local', class: 'tier1-derived', shape: 'utf8', storage: 'base64' },
  { table: 'report_signing_keys', column: 'private_key_encrypted', domain: 'node-local', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'ca_authority', column: 'ca_private_key_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'external_restore_sources', column: 'credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'base64' },
  { table: 'gd_push_config', column: 'api_key_encrypted', domain: 'replicated', class: 'tier1', shape: 'utf8', storage: 'base64' },
  { table: 'integration_config', column: 'config_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'kms_providers', column: 'credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'hex' },
  { table: 'malware_scanner_integrations', column: 'credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'base64' },
  { table: 'notification_config', column: 'sms_auth_token_encrypted', domain: 'replicated', class: 'tier1', shape: 'utf8', storage: 'buffer' },
  { table: 'scheduling_platform_config', column: 'credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'base64' },
  { table: 'sdn_integrations', column: 'api_credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'buffer' },
  { table: 'storage_destinations', column: 'credentials_encrypted', domain: 'replicated', class: 'tier1', shape: 'json', storage: 'base64' },
];

module.exports = { TIER1_COLUMNS: TIER1_COLUMNS };
